add_ox_quiz_category_name(0, "main")
add_ox_quiz_category_name(1, "server")

add_ox_quiz(0, "Czy kowal ma m³ot w prawej rêce?", true)
add_ox_quiz(0, "Czy Ah-Yu ma przy sobie dziecko? ", true )
add_ox_quiz(0, "Czy Wêdruj¹cy Domokr¹¿ca sprzedaje pierœcionki zarêczynowe?", false)
add_ox_quiz(0, "Czy w zagrodzie stajennego jest tylko 3 konie?", false)
add_ox_quiz(0, "Czy Niepoka¿ny Pieszy ma jakieœ opcje?", true)
add_ox_quiz(0, "Czy kapitan stoi na œrodku miasta? ", false)
add_ox_quiz(0, "Czy metin cienia TYLKO wystêpuje na pustyni? ", false)
add_ox_quiz(0, "Czy istnieje straznik wiochy?", false)
add_ox_quiz(0, "Czy Beak-Go ma okulary? ", true )
add_ox_quiz(0, "Czy wieza demonow ma tylko 10 pieter?", false)
add_ox_quiz(0, "Czy pomnik WOELA wystêpuje w V1? ", false)
add_ox_quiz(0, "Czy w Metinie wystêpuje wodospad?", true)
add_ox_quiz(0, "Czy Biolog daje itemki z Item Shop po ukoñczeniu misji?", true)
add_ox_quiz(0, "Czy mo¿na dac koniu imie?", true)
add_ox_quiz(0, "Pytanie Pu³apka--O czy X . WYBIERAJ!!!", true)
add_ox_quiz(0, "Czy na pustyni wystêpuje woda?", true)
add_ox_quiz(0, "Czy to prawda ze piskorz nie daje niewidzialnosc?", false)
add_ox_quiz(0, "Czy mozna miec wszystkie skille na M?", false)
add_ox_quiz(0, "Czy istnieje Zara¿ony Truj¹cy Paj¹k?", false)
add_ox_quiz(0, "Czy Handlarz Zbrojami nie ma corke?", false)
add_ox_quiz(0, "Czy metiny Czerni wystêpuja na 1 mapie?", true)
add_ox_quiz(0, "Czy w M3 wystêpuje Boss?", false)
add_ox_quiz(0, "Czy w metinie pada deszcz?", false)
add_ox_quiz(0, "Czy mo¿na poca³owac gracza z innego królestwa?", false)
add_ox_quiz(0, "Czy Szeroki miecz ma 25% szybkosci ataku?", false)
add_ox_quiz(0, "Czy moge upiec ryby?", true)
add_ox_quiz(0, "Czy Trudny Loch Ma³p nazywa sie Junqsun Dong?", false)
add_ox_quiz(0, "Czy emocje mozesz wyrazac tylko z maska emocji?", false)
add_ox_quiz(0, "Czy respi¹ siê w Metinie ,Metin Chunjo?", false)
add_ox_quiz(0, "Czy 13 serwer nazywa sie Kirian?", false)
add_ox_quiz(0, "Czy na 45 poziomie moge miec Konia Militara?", false)
add_ox_quiz(0, "Czy mozna kupowac u Huan-So?", false)
add_ox_quiz(0, "Czy Zjawa Zó³tego Tygrysa wystêpuje w Swi¹tyni Hwang?", true)
add_ox_quiz(0, "Czy ka¿dy mo¿e wejœc do Lodowej Groty?", false)
add_ox_quiz(0, "Czy Ksiêga Misji Expert dropi z czarnych Orków?", false)
add_ox_quiz(0, "Czy na pierwszym poziomie mozna miec negatywna range?", true)
add_ox_quiz(0, "Czy mozna zabic gracza z 1 lvl?", false)
add_ox_quiz(0, "Pytanie Pu³apka--O czy X . WYBIERAJ!!!", true)
add_ox_quiz(0, "Czy Branzoleta Harmonii mozna handlowac?", false)
add_ox_quiz(0, "Czy Czerwona Mikstura(M) daje 350 p¿/hp?", false)
add_ox_quiz(0, "Czy olejek pi¿mowy jest potrzebny do ulepszania?", false)
add_ox_quiz(0, "Czy jest 12 stron Pamiêtnika Uriela?", false)
add_ox_quiz(0, "Czy Krwisty Kamieñ jest potrzebny do wejœcia do Lodowej Groty?", true)
add_ox_quiz(0, "Czy mozemy teleportowac siê do DT?", false)
add_ox_quiz(0, "Czy mozna na 1 poziomie gildii kupic sobie Ziemie Gildii?", false)
add_ox_quiz(0, "Czy mozna sprzedawac rzeczy z Item Shop?", true)
add_ox_quiz(0, "Czy Srebrny Naszyjnik dodaje inteligencje?", false)
add_ox_quiz(0, "Czy ka¿dy mo¿e zostac GM?", false)
add_ox_quiz(0, "Czy jest Wêgierski Metin?", true)
add_ox_quiz(0, "Czy Grota Wygnañców ma tylko 1 poziom?", false)
add_ox_quiz(0, "Czy metin Jeon-Un wystêpuje w Krainie Gigantów?", false)
add_ox_quiz(0, "Czy stalki dropi¹ nie Tylko z metinów i szkat?", true)
add_ox_quiz(0, "Czy zolw u¿ywa skile?", true)
add_ox_quiz(0, "Czy z ka¿dego Metina mo¿na dropn¹c Kamien Duchowy?", false)
add_ox_quiz(0, "Czy tylko kowal mo¿e ulepszac?", false)
add_ox_quiz(0, "Czy istnieja inne kowale?", true)
add_ox_quiz(0, "Czy bossy w M3 sa agresywne?", false)
add_ox_quiz(0, "Czy Dziki Pies mo¿e zabic 40 lvl?", true)
add_ox_quiz(0, "Czy mo¿na ulepszac KD?", false)
add_ox_quiz(0, "Czy respi¹ siê Smoki?", false)
add_ox_quiz(0, "Czy mozna teleportowac sie do lasu duchow?", true)
add_ox_quiz(0, "Czy wystêpuje ryba Tenchi?", true)
add_ox_quiz(0, "Czy woda Dok zwiêksza szanse na krytyczne uderzenie?", true)
add_ox_quiz(0, "Czy mozna z³owic fasolke Zen?", true)
add_ox_quiz(0, "Czy Per³owe Kolczyki sa na 22 lvl?", false)
add_ox_quiz(0, "Czy fasolka Zen mozna miec Range Rycerska?", false)
add_ox_quiz(0, "Czy rybak mo¿e spalic wêdke?", true)
add_ox_quiz(0, "Czy Paj¹ki maja Bossa?", true)
add_ox_quiz(0, "Czy ulepszajac zbroje na +3 jest potrzebny ulepszacz?", false)
add_ox_quiz(0, "Czy w 39 polowaniu mozna wybrac do zabicia Best Wodz Arahan?", false)
add_ox_quiz(0, "Czy mozna zlowic rybe na Drobnych rybach?", true)
add_ox_quiz(0, "Czy mozna w sklepie sprzedawac smocze monety?", false)
add_ox_quiz(0, "Czy mozna wydropic Bilet Konny?", false)
add_ox_quiz(0, "Czy do ulepszenia Duchowej ZbroiP³ytowej na +6 jest potrzebny Nieznany Talizman?", false)
add_ox_quiz(0, "Czy w metinie mozna wydopic rzeczy +6?", true)
add_ox_quiz(0, "Czy Aranyo ma przy sobie dziecko?", false)
add_ox_quiz(0, "Czy mozna wydropic Muszle?", true)
add_ox_quiz(0, "Czy ¿wój B³ogos³awienstwa mo¿e spalic Ca³y item?", false)
add_ox_quiz(0, "Czy z metinow dropia Smocze Monety?", false)
add_ox_quiz(0, "Czy mirine ma meza?", false)
add_ox_quiz(0, "Czy w Demonicznej wiezy na poziomie 1 wystepuje Demoni Szaman?", true)
add_ox_quiz(0, "Czy Karas regeneruje P¿?", true)
add_ox_quiz(0, "Czy buty z Br¹zu daja szanse na otrucie?", false)
add_ox_quiz(0, "Czy mozna kupic Smocze Znaki?", false)
add_ox_quiz(0, "Czy w Metinie sa Ciasta Ry¿owe?", true)
add_ox_quiz(0, "Czy istnieje Kamieñ przyrody?", false)
add_ox_quiz(0, "Czy Gracz ze Zbroja P³yt. Yin-Yang moze zaprosic 3 lvl do grupy?", false)
add_ox_quiz(0, "Czy gracze moga jezdzic na dziku?", true)
add_ox_quiz(0, "Czy gracze moga jezdzic na dziku na HoolyMt2?", false)
add_ox_quiz(0, "Czy Yu-Hwan jest zdrajca?", false)
add_ox_quiz(0, "Pytanie Pu³apka--O czy X . WYBIERAJ!!!", false)
add_ox_quiz(0, "Czy w Polsce metin jest od 2007 roku?", true)
add_ox_quiz(0, "Czy mozna bronic sie w sukni slubnej?", true)
add_ox_quiz(0, "Czy z Ezotów dropi Pó³ksiê¿ycowy Miecz?", false)
add_ox_quiz(0, "Czy aby przetopic rude potrzebny jest kamien +3?", true)
add_ox_quiz(0, "Czy Elit. Krol Demonów wystêpuje na 2 pietrze DT?", false)
add_ox_quiz(0, "Czy Straznik Wiochy na srodku miasta daje rady?", false)
add_ox_quiz(0, "Czy istnieje Kamien Brzydoty?", false)
add_ox_quiz(0, "Czy mozesz wydropic Perle ze sterty muszli?", false)
add_ox_quiz(0, "Czy Upiorna Zbroja Plyt. +5 daje ci 68 pkt do obrony?", false)
add_ox_quiz(0, "Czy Biolog Chaegirab ma przy sobie jak¹œ torbe?", true)
add_ox_quiz(0, "Czy Deakbae trzyma w prawej rêce topór?", false)
add_ox_quiz(0, "Czy Dozorca trzyma coœ w rêkach?", true)
add_ox_quiz(0, "Czy to prawda, ¿e Hand-Up podczas pierwszej podró¿y zwichne³a sobie kostke o korzen Gangu?", false)
add_ox_quiz(0, "Czy Harang daje jakieœ misje?", true)
add_ox_quiz(0, "Czy Koe-Pung przenosi do V2?", false)
add_ox_quiz(0, "Czy Nakajin jest samotny?", true)
add_ox_quiz(0, "Czy Octavio jest kucharzem?", true)
add_ox_quiz(0, "Czy Seon-Hae ma trzy nogi? ", true)
add_ox_quiz(0, "Czy jakiœ NPC ma przy sobie Papuge?", true)
add_ox_quiz(0, "Czy w Grocie Wygnañców s¹ cztery szkielety? ", true)
add_ox_quiz(0, "Czy 18 serwer to Deimos?", false)
add_ox_quiz(0, "Czy Balso jest zdrajc¹? ", true)
add_ox_quiz(0, "Czy do ulepszenia Siêtego Miecza na +9 jest potrzebne Futro Yeti?", false)
add_ox_quiz(0, "Czy ulepszaj¹c bron, atak podnosi sie zawsze o tyle samo?", true)
add_ox_quiz(0, "Czy do ulepszenia specjlanych broni s¹ potrzebne ulepszacze?", false)
add_ox_quiz(0, "Czy potwór Driada ma 68 lvl?", false)
add_ox_quiz(0, "Czy za Amulet Karmy od staruszki trzeba zap³acic? ", true)
add_ox_quiz(0, "Pytanie Pu³apka--O czy X . WYBIERAJ!!!", true)
add_ox_quiz(0, "Czy wszystkie drzewa w metinie s¹ liœciaste?", false)
add_ox_quiz(0, "Czy dropia Marmury Polimorfii z Silnego Pystynnego Zawadiaki?", false)
add_ox_quiz(0, "Czy Zbroja Hwang to zbroja krolewska?", true)
add_ox_quiz(0, "Czy na 5 pietrze w Wie¿y Demonów jest Kowal?", false)
add_ox_quiz(0, "Czy istnieja bagna w metin2?", false)
add_ox_quiz(0, "Czy mozna sie ozenic z roznica 20 poziomow?", false)
add_ox_quiz(0, "Czy w Kuahklo Dong mozna spotkac Krolowa Pajakow?", true)
add_ox_quiz(0, "Czy Skill na oziomie G9 moze zamienic sie w P?", false)
add_ox_quiz(0, "Czy w m3 mozna zdobyc bronie na 30 lvl?", true)
add_ox_quiz(0, "Czy na Kucyku mozna jezdzic?", false)
add_ox_quiz(0, "Pytanie Pu³apka--O czy X . WYBIERAJ!!!", false)
add_ox_quiz(0, "Czy na 5 pietrze w Wiezy Demonow sa 4 pieczecie?", false)
add_ox_quiz(0, "Czy sa 2 rodzaje dzikiego psa?", false)
add_ox_quiz(0, "Czy istnieje Kamien Metin na 36 lvl?", false)
add_ox_quiz(0, "Czy mozna bez slubu zalozyc pioro ptaka milosci?", false)
add_ox_quiz(0, "Czy pomnik Mok jest na pustyni?", false)
add_ox_quiz(0, "Czy mozna zlowic Zwoj Blogoslawienstwa?", true)
add_ox_quiz(0, "Czy dzieki radzie pustelnika mozna czytac ksiazi bez ograniczen?", false)
add_ox_quiz(0, "Czy na wezowym polu mozna spotkac Zebacza Smugowego?", true)
add_ox_quiz(0, "Czy z Czerwonego Smoka wylatuje Szkatolka?", true)
add_ox_quiz(0, "Czy potrzeba ulepszaczy u gildyjnego kowala?", true)
add_ox_quiz(0, "Czy mozna zaatakowac kogos na slubie?", false)
add_ox_quiz(0, "Czy szaman moze kogos zapalic?", true)
add_ox_quiz(0, "Czy istnieje duch chaosu w metin2?", true)
add_ox_quiz(0, "Czy u Huan-so mozna produkowac eliksiry +100 obrony?", true)
add_ox_quiz(0, "Czy mozna przekazac przywodztwo w gildii?", true)
add_ox_quiz(0, "Czy Yu-Hwan zamienia roze alpejska w miksture?", false)
add_ox_quiz(0, "Czy w v2 sa Male Pajaki?", true)
add_ox_quiz(0, "Pytanie Pu³apka--O czy X . WYBIERAJ!!!", false)
add_ox_quiz(0, "Czy trzeba zabic Czarne Niedzwiedzie do misji od biologa?", false)
add_ox_quiz(0, "Czy Zbroja z CzarnejStali posiada ABS na magie - 19%?", false)
add_ox_quiz(0, "Czy wojownik trzyma miecz w lewej rece?", false)
add_ox_quiz(0, "Czy Chakram trzyma sie w obu rekach?", false)
add_ox_quiz(0, "Czy buty fenixa sa na 59lvl?", false)
add_ox_quiz(0, "Czy Uderzenie Palcem omdlewa?", false)
add_ox_quiz(0, "Czy dropia Marmury Polimorfii z Silnego Pystynnego Zawadiaki?", false)
add_ox_quiz(0, "Czy szaman moze omdlic jakas umiejetnoscia? ", true)
add_ox_quiz(0, "Czy trzeba rude zlota do misji od kowala?", true)
add_ox_quiz(0, "Czy jest polowanie z dzikimi psami?", false)
add_ox_quiz(0, "Czy Syriusz powstaje z Miecza Zadla?", false)
add_ox_quiz(0, "Czy Zbroja Boga Smokow +9 daje 135 pkt. Obrony?", true)

add_ox_quiz(1, "Czy istnieje przedmiot Wolny Miecz?", false)

-- Loading for pools
ox_quiz_flush_pool()
